# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", _drafts] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: mu-omega
google_analytics: mu-omega
title: mu-omega

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: mu-omega

description: Stylish Jekyll Theme
author:
  name: michaelway@github.io
  github: michaelway
  linkedin: #
  bio: About science, coding and other things...
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://dl.dropboxusercontent.com/u/97084569/logo.jpeg

BASE_PATH:

gems:
  - jekyll-paginate
